/* @refresh reload */
import { createSignal, Show, Switch, Match, onMount, onCleanup } from "solid-js"
import { render } from "solid-js/web"
import { invoke } from "@tauri-apps/api/core"
import { getCurrent as getCurrentDeepLink, onOpenUrl } from "@tauri-apps/plugin-deep-link"
import {
  AppBaseProviders,
  AppInterface,
  PlatformProvider,
  ServerConnection,
  checkServerReachable,
} from "@opencode-ai/app"
import "@opencode-ai/app/index.css"
import "./mobile.css"
import { ModeSelector } from "./components/mode-selector"
import { ExtractionProgress } from "./components/extraction-progress"
import { ModelManager } from "./components/model-manager"
import { createPlatform, setPrivateServerFp } from "./platform"
import { writeDebugLog } from "./runtime"
import { ensureLocalLLMLoaded } from "./hooks/use-auto-start-llm"
import { initSpeechListeners, cleanupSpeechListeners } from "./hooks/use-speech"

const root = document.getElementById("root")

// Hide the static loading indicator
const loadingEl = document.getElementById("loading")
if (loadingEl) loadingEl.style.display = "none"

type Mode = "selecting" | "extracting" | "connecting" | "remote-prompt" | "ready"

interface ServerInfo {
  url: string
  username?: string
  password?: string
  variant: "embedded" | "http"
}

function App() {
  const [mode, setMode] = createSignal<Mode>("selecting")
  const [error, setError] = createSignal("")
  const [serverInfo, setServerInfo] = createSignal<ServerInfo | null>(null)
  const [platform, setPlatform] = createSignal<Awaited<ReturnType<typeof createPlatform>> | null>(null)
  const [remoteUrl, setRemoteUrl] = createSignal("")
  const [remoteUsername, setRemoteUsername] = createSignal("opencode")
  const [remotePassword, setRemotePassword] = createSignal("")
  const [remoteChecking, setRemoteChecking] = createSignal(false)
  const [connectStatus, setConnectStatus] = createSignal("Starting local server...")
  const [showModelManager, setShowModelManager] = createSignal(false)

  // Lazy-init platform
  async function ensurePlatform() {
    let p = platform()
    if (!p) {
      p = await createPlatform()
      setPlatform(p)
    }
    return p
  }

  // Handle local mode: extract → connect
  async function handleLocalConnect() {
    setMode("connecting")
    setConnectStatus("Starting local server...")
    try {
      const p = await ensurePlatform()
      const result = await p.startLocalServer?.()
      if (result) {
        setServerInfo({
          url: result.url,
          username: result.username,
          password: result.password,
          variant: "embedded",
        })
        setMode("ready")
      } else {
        setError("Server started but health check timed out after 30s.")
        setMode("selecting")
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
      setMode("selecting")
    }
  }

  // Handle remote mode: prompt for URL
  function handleRemotePrompt() {
    setMode("remote-prompt")
  }

  async function handleRemoteConnect() {
    const url = remoteUrl().trim()
    await writeDebugLog(`[FIX-ACTIVE-V2] handleRemoteConnect raw=${url}`)
    if (!url) return
    const normalized = (/^https?:\/\//.test(url) ? url : `http://${url}`).replace(/\/+$/, "")
    const p = await ensurePlatform()
    const username = remoteUsername().trim() || undefined
    const password = remotePassword() || undefined
    await writeDebugLog(`[FIX-ACTIVE-V2] normalized=${normalized} user=${username} hasPass=${!!password}`)
    setError("")
    setRemoteChecking(true)
    const check = await checkServerReachable(p, normalized, username, password)
    await writeDebugLog(`[FIX-ACTIVE-V2] preflight result ok=${check.ok} msg=${check.ok ? "OK" : check.message}`)
    setRemoteChecking(false)
    if (!check.ok) {
      setError(check.message)
      return
    }
    await p.setDefaultServer?.(normalized as any)
    setServerInfo({ url: normalized, variant: "http", username, password })
    setMode("ready")
  }

  // SHA-256 fingerprint generated by desktop tls.rs is colon-separated uppercase
  // hex (32 pairs → 95 chars). Anything else is rejected to prevent poisoning
  // of _privateFp from a malicious deep link.
  const FP_RE = /^[0-9A-F]{2}(:[0-9A-F]{2}){31}$/

  // Only accept URLs we can actually reach over TLS (the self-signed cert path
  // requires https). http(s)://… bare host form is allowed; anything else
  // (javascript:, file:, data:, opencode:) is refused.
  function isSafePairingUrl(u: string): boolean {
    let parsed: URL
    try { parsed = new URL(u) } catch { return false }
    return parsed.protocol === "https:" || parsed.protocol === "http:"
  }

  // Accept pairing deep links of the form `opencode://connect?url=...&user=...&pwd=...`
  // (generated by the desktop Settings → Remote Access QR code). Returns true if
  // the link was understood and the form was populated, false otherwise.
  //
  // SECURITY: we deliberately do NOT auto-submit the connection. Even though
  // the URL was typically opened by scanning the on-device QR, the intent can
  // also be triggered by a hostile web page — so the user must confirm by
  // tapping "Connect" on the pre-filled form.
  function applyPairingDeepLink(raw: string): boolean {
    let parsed: URL
    try {
      parsed = new URL(raw)
    } catch {
      return false
    }
    if (parsed.protocol !== "opencode:") return false
    // URL.hostname is empty for `opencode://connect` (no `//` authority), so the
    // command lives in pathname. Support both `opencode://connect?...` and
    // `opencode:connect?...` for robustness.
    const command = parsed.hostname || parsed.pathname.replace(/^\/+/, "")
    if (command !== "connect") return false

    const url = parsed.searchParams.get("url")
    if (!url || !isSafePairingUrl(url)) return false

    const user = parsed.searchParams.get("user") ?? "opencode"
    // Bound user/pwd size — prevents absurd URLs from clogging state.
    const pwd = parsed.searchParams.get("pwd") ?? ""
    if (user.length > 128 || pwd.length > 512) return false

    // Fingerprint TLS : active le mode self-signed pour ce serveur privé.
    // Only persist the fingerprint if it matches the exact format produced by
    // desktop tls.rs; otherwise fall back to a null fingerprint (plain TLS).
    const fpRaw = parsed.searchParams.get("fp")
    const fp = fpRaw && FP_RE.test(fpRaw) ? fpRaw : null
    setPrivateServerFp(fp)

    setRemoteUrl(url)
    setRemoteUsername(user)
    setRemotePassword(pwd)
    setMode("remote-prompt")
    return true
  }

  onMount(() => {
    // A.4-part1: pause/resume detection via visibilitychange.
    // On background: notify Rust (placeholder for foreground-service keepalive).
    // On resume: health-check and emit reload event if server died.
    let wasHidden = false
    const visibilityHandler = async () => {
      if (document.hidden) {
        wasHidden = true
        try { await invoke("llm_idle_tick") } catch {}
      } else if (wasHidden) {
        wasHidden = false
        try {
          const ok = await invoke<boolean>("check_llm_health", { port: null })
          if (!ok) {
            window.dispatchEvent(new CustomEvent("llm-needs-reload"))
          }
        } catch {}
      }
    }
    document.addEventListener("visibilitychange", visibilityHandler)
    onCleanup(() => document.removeEventListener("visibilitychange", visibilityHandler))
  })

  onMount(() => {
    // Cold-start: the app may have been launched *by* a deep link intent.
    void getCurrentDeepLink()
      .then((urls) => {
        if (!urls) return
        for (const u of urls) if (applyPairingDeepLink(u)) break
      })
      .catch(() => undefined)

    // Warm-start: the app was already running when the intent fired.
    let unlisten: (() => void) | undefined
    void onOpenUrl((urls) => {
      for (const u of urls) if (applyPairingDeepLink(u)) break
    })
      .then((fn) => {
        unlisten = fn
      })
      .catch(() => undefined)
    onCleanup(() => unlisten?.())
  })

  return (
    <>
    <Show when={showModelManager()}>
      <ModelManager
        onClose={() => setShowModelManager(false)}
        serverUrl={serverInfo()?.url}
        serverAuth={serverInfo()?.username ? { username: serverInfo()!.username!, password: serverInfo()!.password! } : undefined}
      />
    </Show>
    <Switch>
      <Match when={mode() === "selecting"}>
        <ModeSelector
          onLocal={() => setMode("extracting")}
          onRemote={handleRemotePrompt}
          onExtract={() => setMode("extracting")}
        />
        <Show when={error()}>
          <div style={{
            position: "fixed", bottom: "24px", left: "24px", right: "24px",
            padding: "12px 16px", "border-radius": "8px",
            background: "#7f1d1d", color: "#fca5a5", "font-size": "14px",
            "text-align": "center",
          }}>
            {error()}
          </div>
        </Show>
      </Match>

      <Match when={mode() === "extracting"}>
        <ExtractionProgress
          onComplete={() => handleLocalConnect()}
          onError={(msg) => { setError(msg); setMode("selecting") }}
        />
      </Match>

      <Match when={mode() === "connecting"}>
        <div style={{
          display: "flex", "flex-direction": "column", "align-items": "center",
          "justify-content": "center", height: "100vh", gap: "16px",
          background: "#0a0a0a", color: "#e5e5e5",
          "font-family": "system-ui, -apple-system, sans-serif",
        }}>
          <div style={{ "font-size": "18px", "font-weight": "600" }}>{connectStatus()}</div>
          <div style={{ color: "#888", "font-size": "14px" }}>Waiting for health check...</div>
          {/* Simple spinner */}
          <div style={{
            width: "32px", height: "32px", border: "3px solid #333",
            "border-top-color": "#3b82f6", "border-radius": "50%",
            animation: "spin 1s linear infinite",
          }} />
          <style>{`@keyframes spin { to { transform: rotate(360deg) } }`}</style>
        </div>
      </Match>

      <Match when={mode() === "remote-prompt"}>
        <div style={{
          display: "flex", "flex-direction": "column", "align-items": "center",
          "justify-content": "center", height: "100vh", padding: "24px", gap: "24px",
          background: "#0a0a0a", color: "#e5e5e5",
          "font-family": "system-ui, -apple-system, sans-serif",
        }}>
          <h1 style={{ "font-size": "24px", "font-weight": "700", margin: "0" }}>
            Connect to Server
          </h1>
          <p style={{ color: "#888", "font-size": "14px", margin: "0", "text-align": "center", "max-width": "320px" }}>
            Enter the URL of your OpenCode server running on your PC
          </p>
          <input
            type="url"
            placeholder="192.168.1.100:3000"
            value={remoteUrl()}
            onInput={(e) => setRemoteUrl(e.currentTarget.value)}
            onKeyDown={(e) => e.key === "Enter" && handleRemoteConnect()}
            style={{
              width: "100%", "max-width": "320px", padding: "14px 16px",
              "border-radius": "10px", border: "1px solid #333",
              background: "#1a1a1a", color: "#e5e5e5", "font-size": "16px",
              outline: "none",
            }}
          />
          <input
            type="text"
            autocapitalize="none"
            autocomplete="username"
            placeholder="Username"
            value={remoteUsername()}
            onInput={(e) => setRemoteUsername(e.currentTarget.value)}
            onKeyDown={(e) => e.key === "Enter" && handleRemoteConnect()}
            style={{
              width: "100%", "max-width": "320px", padding: "14px 16px",
              "border-radius": "10px", border: "1px solid #333",
              background: "#1a1a1a", color: "#e5e5e5", "font-size": "16px",
              outline: "none",
            }}
          />
          <input
            type="password"
            autocapitalize="none"
            autocomplete="current-password"
            placeholder="Password"
            value={remotePassword()}
            onInput={(e) => setRemotePassword(e.currentTarget.value)}
            onKeyDown={(e) => e.key === "Enter" && handleRemoteConnect()}
            style={{
              width: "100%", "max-width": "320px", padding: "14px 16px",
              "border-radius": "10px", border: "1px solid #333",
              background: "#1a1a1a", color: "#e5e5e5", "font-size": "16px",
              outline: "none",
            }}
          />
          <Show when={error()}>
            <div style={{
              width: "100%", "max-width": "320px",
              padding: "10px 14px", "border-radius": "8px",
              background: "#7f1d1d", color: "#fca5a5",
              "font-size": "14px", "text-align": "center",
            }}>
              {error()}
            </div>
          </Show>
          <div style={{ display: "flex", gap: "12px", width: "100%", "max-width": "320px" }}>
            <button
              onClick={() => setMode("selecting")}
              disabled={remoteChecking()}
              style={{
                flex: "1", padding: "14px", "border-radius": "10px",
                border: "1px solid #333", background: "#1a1a1a",
                color: "#888", "font-size": "15px", cursor: remoteChecking() ? "not-allowed" : "pointer",
                opacity: remoteChecking() ? "0.5" : "1",
              }}
            >
              Back
            </button>
            <button
              onClick={handleRemoteConnect}
              disabled={remoteChecking()}
              style={{
                flex: "1", padding: "14px", "border-radius": "10px",
                border: "1px solid #3b82f6", background: "#1e3a5f",
                color: "#e5e5e5", "font-size": "15px", cursor: remoteChecking() ? "wait" : "pointer",
                "font-weight": "600",
                opacity: remoteChecking() ? "0.7" : "1",
              }}
            >
              {remoteChecking() ? "Connecting..." : "Connect"}
            </button>
          </div>
        </div>
      </Match>

      <Match when={mode() === "ready" && serverInfo() && platform()}>
        <FullApp
          platform={platform()!}
          serverInfo={serverInfo()!}
          onOpenModelManager={() => setShowModelManager(true)}
        />
      </Match>
    </Switch>
    </>
  )
}

function FullApp(props: {
  platform: Awaited<ReturnType<typeof createPlatform>>;
  serverInfo: ServerInfo;
  onOpenModelManager?: () => void;
}) {
  // Listen for "open-model-manager" custom event from the model selector
  onMount(() => {
    const handler = () => props.onOpenModelManager?.()
    window.addEventListener("open-model-manager", handler)
    onCleanup(() => window.removeEventListener("open-model-manager", handler))
  })

  // Auto-start local LLM when model is selected
  onMount(() => {
    const handler = (e: CustomEvent) => {
      const { providerID, modelID } = e.detail ?? {}
      ensureLocalLLMLoaded(providerID, modelID)
    }
    window.addEventListener("model-selected" as any, handler as any)
    onCleanup(() => window.removeEventListener("model-selected" as any, handler as any))
  })

  // Wire STT/TTS listeners — mic button dispatches `stt-start`/`stt-stop`,
  // copy button dispatches `tts-toggle`. See packages/app/src/components/
  // prompt-input.tsx for the UI side.
  onMount(() => {
    initSpeechListeners()
    onCleanup(cleanupSpeechListeners)
  })
  const connection = (): ServerConnection.Any => {
    if (props.serverInfo.variant === "embedded") {
      return {
        type: "sidecar",
        variant: "embedded",
        http: {
          url: props.serverInfo.url,
          username: props.serverInfo.username,
          password: props.serverInfo.password,
        },
      }
    }
    return {
      type: "http",
      http: {
        url: props.serverInfo.url,
        username: props.serverInfo.username,
        password: props.serverInfo.password,
      },
    }
  }

  const defaultKey = () => ServerConnection.key(connection())
  const servers = () => [connection()]

  return (
    <PlatformProvider value={props.platform}>
      <AppBaseProviders>
        <AppInterface
          defaultServer={defaultKey()}
          servers={servers()}
        />
      </AppBaseProviders>
    </PlatformProvider>
  )
}

render(() => <App />, root!)
